#
# Example config file
#
input:
# Input from COM port - device: COM1@9600
# Input from UDP - device: 127.0.0.1:
  device: COM1@4800
# Sentences: hdm, hdt, ths
  heading_sentence: hdt
output:
# Output to UDP - device: 127.0.0.1:2947
# Output to COM port - device: COM1@9600
  device: 127.0.0.1:2947
# Sentences: gpgga, ratll
  position_sentence: ratll
ugps_url: http://192.168.2.94
