name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        go get .

    - name: Build
      run: make

    - name: Unit-test
      run: make test

    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ugps-nmea
        path: build
